### ISSUE TITLE
Unable to use private registry

### ISSUE THREAD

**Issue by VogonogoV** [rancherio/rancher#1020]
I've got a self-hosted docker registry. I would like to let rancher pull images and deploy the containers from it. I'm using `sudo docker run -d --restart=always -p 8080:8080 rancher/server` and added a custom registry.

First of all, my interface doesn't look like: http://rancher.com/rancher-adds-support-for-private-docker-registries/. I cannot select the registry when selecting an image.

So instead I enter `<redacted-registry-name>/<image-name>`. The container shows the error: `HTTPS endpoint unresponsive and insecure mode isn't enabled`. I removed the registry and added it again but now starting with `https://` however it still gives the same error. The registry uses a self-signed certificate.

I am unable to use my private registry with Rancher at the moment. Is this a bug or am I missing instructions?

**Comment by hibooboo2** [comment]
@VogonogoV can you do a docker inspect on you rancher/server container and tell me what the ```CATTLE_RANCHER_SERVER_IMAGE ``` environment variable is set to.

**Comment by hibooboo2** [comment]
```openssl s_client -showcerts -connect ${host}:${port} </dev/null 2>/dev/null|openssl x509 -outform PEM > ${selfsigned.crt}
cp ${selfsigned.crt} /etc/docker/certs.d/${registry.domain}/ca.crt```
@VogonogoV Running these two lines on your machine where you are trying to deploy the container should work as this will download the crt from your registry and then copy it to the proper spot for docker to recognize it. Let me know if this works / doesn't

**Comment by VogonogoV** [comment]
The `CATTLE_RANCHER_SERVER_IMAGE` is `v0.22.0-rc2`.

I'm currently trying to deploy on the same machine as the rancher server. I added the certificate and restarted docker but it still gives the same error. I verified by doing a `sudo docker login <registry>` and it works, I can pull images as well. 

> Also in order to use a registry with a self signed cert you have to change the hosts docker daemon.

Do you mean adding `--insecure-registry <registry>` to the docker daemon? I did that as well.

**Comment by hibooboo2** [comment]
@VogonogoV I found the cause of the problem and will be putting in a pr to fix it soon. Ill get back to you later when it is in so you can try it again.

**Comment by sangeethah** [comment]
Private registry works with server version - v0.23.0-rc6

You should be able to launch containers using private registries by following these steps: 
1.If you are working with self signed certs :
Following commands need to be run on each of the hosts where you expect the containers to be started:
DOMAIN and PORT are the domain and port where the private registry is hosted

openssl s_client -showcerts -connect ${DOMAIN}:${PORT} </dev/null 2>/dev/null|openssl x509 -outform PEM >ca.crt
sudo cp ca.crt /etc/docker/certs.d/${DOMAIN}/ca.crt
cat ca.crt | sudo tee -a /etc/ssl/certs/ca-certificates.crt
sudo service docker restart

on the rancher server , add a registry for your private registry.
Add a container using an image from your private registry. Containers will start successfully.

2.If you are using private registries with no authentication :
Add  --insecure-registry ${DOMAIN}:${PORT} to the docker daemon flags and restart docker. 

Add a container using an image from your private registry. Containers will start successfully.

Note - when restarting docker on the host , you may encounter issues with network Agent being stuck in “starting” state because of  #931. To workaround the issue , reboot the host.
