### ISSUE TITLE
Updating images

### ISSUE THREAD

**Issue by willowandcreek** [rancherio/rancher#1062]
Hi,

Is there a way to "update" a service's image? For example, when you push an update to an image you generally tag it with a new tag. So how do I modify a service image's tag so that a new version of the service can be deployed? Currently once a service is started for the first time, it doesn't allow you to change the image spec. Or is there something I have missed?

Thanks

**Comment by will-chan** [comment]
The best way right now is to either setup a LB service or a DNS service to "front" your app service.  Let's call that AppV1.  All consumers of AppV1 would access it via a LB or DNS.  Once you want to update the image, you can create a AppV2 service, do your local testing, and add it to either the LB or DNS service.  You can then stop or delete your AppV1 service when you are content that AppV2 is working fine.  We do plan on adding a "rolling update" CLI tool later to assist with this too.

**Comment by willowandcreek** [comment]
Thanks for the info. I guess I was looking at the service as being something I just setup once and then "upgrade" versions for it. Also I noticed that in v0.23.0-rc6 we are able to clone a service after its been started. So I guess cloning will work for now. 

Is there any info you can share about the "rolling update" feature?

**Comment by willowandcreek** [comment]
Please disregard the above. I tried the cloning approach and noticed that the LB's edit screen allows me to switch to a new service. So this works perfectly for my scenario! I just need to have another LB which is a so called "staging" LB which will point to my latest version and switch the "production" LB once everything is verified! Perfect perfect!

Loving Racher more n more with every passing minute! :+1: :smile:

**Comment by will-chan** [comment]
Yes, that is exactly what our LB and DNS service is used for.  Our rolling upgrade feature is something we'll be working on soon after our beta launch.  The only thing I can share right now is that it will most likely be a CLI/API option that will allow you to:

* Specify to rolling upgrade "serviceV1" to "serviceV2"
* Specify the # of containers, or % of the service to stop on "serviceV1" while bring up the same number on "serviceV2"
* Specify a time interval between each action

We felt that with the LB/DNS Service, you can already achieve the upgrade scenario as described above and this would only be a convenience feature rather than a blue/green upgrade scenario that is currently already supported.

Glad you are finding great use with Rancher!

**Comment by willowandcreek** [comment]
Awesome. I think the LB works really well. I haven't tried integrating with the Rancher API directly, but I think that should work pretty well.

When you refer to the "DNS" service, are you referring to "Service Alias"?

**Comment by will-chan** [comment]
Yeah, it got renamed to Service Alias.

**Comment by sepiroth887** [comment]
This is great for stateless services. I have a more specific use case for rolling updates though: 

imagine you run a zookeeper cluster. Now you want to ensure quorum at all times above the value configured in the config. If i want to update the image of that cluster of containers, i would have to do them one by one or 2 by 2 depending on how many can be removed simultaneously. This is pretty tedious :D 

Is the rolling update feature able to cope with said scenario? And how flexible would it be? E.g. would I be able to specify updating half of a cluster at once? How would healthchecks work to ensure node A is up before node B is taken offline. 

Your doing awesome work! Keep it up!
