### ISSUE TITLE
Host Registration page is not shown when access control is on

### ISSUE THREAD

**Issue by deniseschannon** [rancherio/rancher#1090]
v0.23.0-rc6

Steps to Reproduce
1. Start a new Rancher server
2. Turn on Access Control
3. Add Hosts

Result: Goes immediately to the Add Hosts options. 

Expected Result: Since it's the first time we go to the add host page, typically Host Registration is displayed first.

**Comment by vincent99** [comment]
@deniseschannon @will-chan Open for discussion but this was added as a "feature" at the request of @ibuildthecloud.  If you turn on auth we figured the URL you used is probably going to be accessible so I set the `api.host` setting to the browser's domain after auth is turned on.  Since it is set, you don't need to be sent there when adding the first host.

**Comment by will-chan** [comment]
Oh, that's good enough.  I just want to make sure that GMS is started.

**Comment by deniseschannon** [comment]
I can confirm that GMS does start and no issues with launching a host using a cloud provider.

Verified v0.24.0-rc3
