### ISSUE TITLE
Ports and link disappear after service creation

### ISSUE THREAD

**Issue by joshuacox** [rancherio/rancher#1100]
I've done this a couple of times now using 0.3.1 rancheros, I create a new service using this as base:
https://registry.hub.docker.com/u/joshuacox/docker-icinga2/

I add in all the ports:
45664 80
45664 80/udp
5665 5665
5665 5665/udp
5667 5667
5667 5667/udp

and env vars:
 ICINGA_DB_USER=icinga2
 ICINGA_DB_PASSWORD=pass123
 ICINGAWEB_DB_USER=icinga_web
 ICINGAWEB_DB_PASSWORD=pass123
 ICINGAWEB_DATABASE=icinga_web

and I add a link to DB:mysql

but when the container starts, it forgets from what I can tell everything, and when I relink the DB as mysql it acts like none of the ports were assigned?  I've got a few other things working great in rancher so it must be something I've done wrong with either the container or something else.  Perhaps just too many ports?

**Comment by deniseschannon** [comment]
What version of Rancher are you running?  You can do a docker inspect on the rancher server container, which will show you the version in the Environment Variables. I was able to get something running in v0.23.0-rc6, which is the current latest version. 

Notes: I had to add in an additional env variable from your list in order to get it running. 
MYSQL_PORT_3306_TCP=3306

Using the "managed" network, I was able to see the <host_ip>:45664 to access the container.  I checked the iptables of the host and found the TCP rules being created, but it doesn't look like the UDP rules are being created, so I created an issue (#1124). It's actually an issue depending on which port protocol you put in first. The port mapping is working correctly for the 3 unique ports.

Can you try adding your container and check to see the port mapping for 80 is working for you by going to the <host_ip>45564?

Also, if you have port conflicts on your host and you've added the container through the "Add Container" button on the host, then we will spin up the container even though it won't work due to the port conflicts. If you use "Add Container" from the container page, we'll try and schedule the placement of your container onto whatever host has no port conflicts. If there are no hosts with no port conflicts, it will fail.

**Comment by joshuacox** [comment]
Removing the udp statements did get the container to start normally.  I can certainly live without udp for now, so that's not a game stopper at all.  At least for icinga, I'm certain that will need to be working for some other things though (for example DNS uses udp primarily, except in the case of zone transfers in which you surely want tcp on, you don't just fire and forget a zone transfer).  If I can supply any other pertinent info please let me know, otherwise I'm closing this for now and subscribing to https://github.com/rancherio/rancher/issues/1124

```
"Env": [
            "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
            "DEBIAN_FRONTEND=noninteractive",
            "CATTLE_HOME=/var/lib/cattle",
            "DEFAULT_CATTLE_API_UI_INDEX=//releases.rancher.com/ui/0.24.0",
            "CATTLE_DB_CATTLE_DATABASE=mysql",
            "S6_SERVICE_DIR=/service",
            "CATTLE_RANCHER_SERVER_IMAGE=v0.23.0-rc6",
            "DEFAULT_CATTLE_MACHINE_EXECUTE=true"
        ],
```
