### ISSUE TITLE
Container creation failure - New Service

### ISSUE THREAD

**Issue by Rucknar** [rancherio/rancher#1190]
**Summary**
Creating a new service for a single node gets stuck in loop trying to start the container but failing.

**Steps to replicate**
Fresh management host on AWS, two hosts built using rancher on AWS.
Create new service, use the stock mysql container from the library, choose one container and set the defaults, do nothing in advanced options. The service is created but when started the container exits and gets stuck in a cycle of attempting to start and failing. Service is listed as degraded. 

Adding a lone container using this image outside of the service works just fine.

**Comment by deniseschannon** [comment]
When adding a lone container of the mysql image outside of service, it should go to an "Inactive" state, which is indicated with the solid red circle next to it. When viewing the logs, it will indicate that the environment variable for "MYSQL_ROOT_PASSWORD" was not passed through. This can be added in the Advanced Options section.

For the service, since the container will never actually get started (due to the missing env var), it will continue try to launch the container on a host over and over again. Basically, for services, we'll keep trying until we get a container in an active state.

**Comment by Rucknar** [comment]
RIght you are! Interestingly i wasn't getting any errors into the 'view logs' screen which just sticks (in this case) on initialising. That's a seperate issue though, happy to close this one off.
