### ISSUE TITLE
Should API Keys be shared across members (users)

### ISSUE THREAD

**Issue by tfiduccia** [rancherio/rancher#1203]
Since the Secret Key will be encoded at some point, people having access to keys they did not create seems useless, except to change the name and description of a key they cannot use and did not create.  

Can only see API Keys that user created.

**Comment by vincent99** [comment]
"Yes";  The credentials are owned by the project and all the users have access to them.  They are likely to be put into configuration files and password vaults that are shared and anybody should be able to deactivate one that gets compromised, etc.

It is possible to create an API key for your user instead of a project, but there is not a UI control for that yet.  Those would not be shared between users.
