### ISSUE TITLE
Load balancer not working

### ISSUE THREAD

**Issue by qrpike** [rancherio/rancher#1289]
I have tried everything possible. The service is accessible via its port and returns a valid HTTP response. But when I try to add a load balancer, I get a 503 Service Unavailable. I guess the load balancer can't reach the service, but I have tried everything to ensure it can.

And suggestions?

**Comment by vincent99** [comment]
The load balancer targets point at the internal IP (10.42.x.y) and port of a container, so make sure you are setting the target port to the one the container is actually listening on.  Also if you have a healthcheck configured on the balancer it must be succeeding before the balancer will send traffic to it.  If your target container logs access you should be able to see requests to it.  You could also try something generic like the `nginx` image, it exposes `80` and `443` by default.

**Comment by deniseschannon** [comment]
When you say the service is accessible via its port, how are you checking that the service is available?

Are you setting up a load balancer or a load balancer service? If you are using a load balancer and have a port conflict, the load balancer will still launch the container, but the port of your service might be overwritten. This issue provides some context on why that is:  https://github.com/rancherio/rancher/issues/435. If you use a load balancer service, the host allocator (what decides which host to launch the load balancer on) will make sure to select a host with no port conflict. 
Finally just to check, are you sure that the port is open on your host that the load balancer agent is on? For example, on an EC2 instance, you'll need to make sure to add them to the security group.

**Comment by qrpike** [comment]
This was very confusing. It works now that I point the port to the internal port of the service in the container.

I went to school for design and UI/UX, so I'm not just talking rubbish.

When I setup my blog service, I exposed the port as 9090. When setting up my LB service for my blog service, it seems as I would point my LB service at the exposed port of the blog service, not the internal port. It would be GREATLY appreciated I'm sure by many, if this was more apparent, or the how-to page had this notice in it.

Thanks again for the great software, keep up the good work!

**Comment by vlad-pustiu** [comment]
I banged my head on the desk for 4 hours with the AWS ELB and the Rancher Load Balancer not working as I eventually found out that I was configuring the Rancher LB to point to the exposed port of the container and all I had to do was point to the internal port.

**Comment by Binarytales** [comment]
@vlad-pustiu Your comment just saved me from an afternoon of head scratching. This is not at all clear in the documentation. Thank you for such a clear and helpful comment.

**Comment by vlad-pustiu** [comment]
Glad I could help :)

**Comment by gabrielgarza** [comment]
@vlad-pustiu Thanks for posting your answer! I think I'm having the same issue. Would you be able to tell me how can I figure out which is the internal port? Essentially my app is a rails app that is listening on port 3000.

When I create my service called web, I have the option to select Port mapping. Should I leave this blank or do something like 80:3000?

When I create my load balancer, I can choose my target (web), and then a port. should this be port 80 or port 3000? and should this be used in combination with the port of the web service mentioned above?

If I create my web service and leave the port mapping blank, then create a load balancer with port 80 -> target web on port 3000, when I visit the IP address I get a 503 error. Would really appreciate your help! Thank you

**Comment by vlad-pustiu** [comment]
Hi Gabriel,

When you create your web service you do not have to expose a port on the
machine. When you map the ports like 80:3000 it means that your container's
3000 port (the internal port) is mapped to the server's 80 port (the
external port).
The load balancer uses rancher's network as it is only a container itself
so it is sufficient to just select the target when you create it, in your
case the web service and the internal port that your container listens to,
in your case 3000.
Make sure you have the ports: directive in your docker-compose.yml like
this:
ports:
 - "3000"
I think that the web service has to have the container port specified.
As for the 503 you have to get creative, see some logs.
If I were you I would make sure that my app is up and running on a host
port and just after that add the load balancer.

Hope it will help you, keep us posted :)

**Comment by gabrielgarza** [comment]
@vlad-pustiu Hey Vlad thank you for your quick reply.

The issue is now resolved.

I'm using AWS EC2 machines, interestingly the IP address that appears in the rancher UI for the machine is different than the ip address that I see in my EC2 dashboard for that machine. Turns out I had the correct setup from the start (which is just like you mention), but I was trying to access the service through the IP address in the rancher UI. Using the EC2 public DNS name of the machine which has the load balancer ec2-XX-XXX-XXX-XXX.us-west-2.compute.amazonaws.com works perfectly.

As for the 503, I'm not really sure what caused it. I created a service and in the Port Mappings I did Public Host Port 3000 and Private Container Port 3000 (i was just testing out anything I could). And this actually sent my rancher server into a death spiral. It tried to start the service but gave an error. Then I tried deleting the service as it was in a failed state. Then the whole rancher UI became inaccessible and never loaded again. I could SSH but could not load the UI. I even tried rebooting the EC2 instance and did not fix it. Thankfully I'm just testing this out, and I terminated the entire rancher server instance and started again from scratch with a new one. But it is scary to think something like this could happen. I'm not sure if the fact that I did the 3000:3000 port mapping was the cause. Sorry for the long post, but just trying to add details while it's fresh.

Thanks again
