### ISSUE TITLE
updating existing services

### ISSUE THREAD

**Issue by defunctzombie** [rancherio/rancher#1310]
I don't see a way to update an existing service (like set new scheduling options, env vars, etc). Is this intentional with the idea being that I should always be cloning services? Does make it a bit more tedious in the manual setup phase but I suppose another idea would be to build more automation tools on top of the basics and do less manual things.

**Comment by ibuildthecloud** [comment]
This is slightly intentional.  Because docker doesn't allow you to change things after the fact for containers the only way you could edit a service is to scale to zero.  Instead there is a clone action on a service in the UI that allows you to edit before you save it.  The other simple thing is to just use rancher-compose which makes it faster because you just edit the template then rm/up on that service.

**Comment by defunctzombie** [comment]
Makes sense. Tho when you remove the service it is also removed from any Lb
services (as a link). So a simple rm/up is not enough and you have to
re-attach to LB as well.

**Comment by ibuildthecloud** [comment]
rancher-compose will take of this.  If you do an up on an existing service all it checks is that 1) it's activated 2) the links point the right place.

So just do edit file rm/up editted service and up on the LB to remap links

**Comment by defunctzombie** [comment]
Oh interested, didn't realize that. Thank you for the tip!
