### ISSUE TITLE
Instance stuck in "post-network" state when activating service that is linked to dns service.

### ISSUE THREAD

**Issue by sangeethah** [rancherio/rancher#1311]
Server version - V0.25.0-rc2

I was doing scenarios relating to a service linked to dns service which is linked to multiple services  , scenarios like scaling services , stopping/starting instances.
After few scenarios , I see that one of the instance gets stuck in "post-network" state when activating service that is linked to dns service. It stays in "starting" state forever.

I activate services and and add servicelinks between services in parallel .
 
    service.activate()
    consumed_service.activate()
    consumed_service1.activate()
    dns.activate()

    service.addservicelink(serviceId=dns.id)
    dns.addservicelink(serviceId=consumed_service.id)
    dns.addservicelink(serviceId=consumed_service1.id)

After this , I am not able to ping between containers from other host and the host where I see the container stuck on "Starting" state at "Post Network" state. 

Is the instance that is stuck in "post-network" causing the network connectivity issues  to the host ?

**Comment by alena1108** [comment]
@sangeethah instance being stuck in post-network state is not causing network connectivity issues. This bug is in the cattle code. In instance post start we shouldn't wait for serviceExposeMap.activate as the instnace.start and serviceExposeMap.activate are invoked sequentially, and there is a possible race condition when:

1) instance.start is invoked, but fails. So serviceExposeMap.activate is never called.
2) on the second instance.start retry, we wait for the serviceExposeMap to become active assuming that the serviceExposeMap.activate was called already (false assumption)

**Comment by alena1108** [comment]
The fix is in master now. But unfortunately there is no easy way to test it. @sangeethah just monitor validation tests runs to see if you notice it happening again.

**Comment by sangeethah** [comment]
This issue has not been observed in the last few runs when executing DNS related test cases.
