### ISSUE TITLE
Using same hostname when adding a host via machine doesn't work

### ISSUE THREAD

**Issue by will-chan** [rancherio/rancher#139]
If you use the same hostname for the same Machine Driver (i.e. VB), it will error out.  However, Cattle server will continuously send the create request down even though there's no way this will ever fix itself unless the hostname changes.

**Comment by cjellick** [comment]
This is because virtualbox doesn't allow vms with duplicate names. Digital ocean does, so you won't see this error with DO (or most of the other cloud providers).

So, I don't think we should enforce name uniqueness per driver or user. 

The fact that cattle keeps retrying the create request is by design on my part, but we can revisit. My understanding of the intended workflow for cattle processes is that failing events should be retried by cattle until operator/user intervention cancels them. Of course, we currently aren't doing a good job of conveying failures to the user for machines, so [updating and conveying status to the user](https://github.com/rancherio/go-machine-service/issues/10) may be a more general way to address this issue.

**Comment by will-chan** [comment]
The crux of the problem isn't really the hostname uniqueness check.  It is more of what we should if the go-machine-service isn't able to fully process a request.  Today, we do nothing and Cattle will continue to re-send the request in the hopes that it will correct itself (in this particular example, it is unlikely it will ever correct itself and also, the user doesn't know it was the same name issue that was causing this problem).    Should we add a retry attempt before ultimately sending an error/processed event back to Cattle?

**Comment by will-chan** [comment]
This has been resolved with the ability to send error messages back to Cattle.
