### ISSUE TITLE
Unable to register agents after authentication is enabled

### ISSUE THREAD

**Issue by usmanismail** [rancherio/rancher#142]
After enabling authentication on my rancher server I am no longer able to register any agents. 

I keep getting the following error:

	docker run --rm -it --privileged -v /var/run/docker.sock:/var/run/docker.sock rancher/agent http://104.236.12.86:8080/v1/scripts/AE6F757B8475E1CDF8ED:1425265200000:nWQ1Uqsf3XBdYHK0hPQgAJHZIq0
	INFO: Attempting to connect to: http://104.236.12.86:8080/v1
	ERROR: http://104.236.12.86:8080/v1 is not accessible
	ERROR: http://104.236.12.86:8080/v1 is not accessible
	ERROR: http://104.236.12.86:8080/v1 is not accessible
	ERROR: http://104.236.12.86:8080/v1 is not accessible

This despite the fact that I am able to reach the specified port and get past the authentication If I use curl manually both on the host and inside the agent container.

	curl http://104.236.12.86:8080/v1/scripts/C7AB12D134CFB0EBEAC3:1425265200000:0WudVGMxIUIjk3nH3GVyOVG0s
	#!/bin/sh

	export CATTLE_REGISTRATION_ACCESS_KEY="registrationToken"
	export CATTLE_REGISTRATION_SECRET_KEY="C7AB12D134CFB0EBEAC3:1425265200000:0WudVGMxIUIjk3nH3GVyOVG0s"
	export CATTLE_URL="http://104.236.12.86:8080/v1"
	export DETECTED_CATTLE_AGENT_IP="104.236.224.92"

**Comment by cloudnautique** [comment]
I think I know what is happening... it looks like there is a bug in the startup logic of the agent. We are not dumping the keys to the logs which is why the URL is truncated in your first snippet. The bug is that we are using the shortened URL without authentication and testing that we can connect to it. (We aren't because we are not authenticated)

I'll verify, and update.

**Comment by usmanismail** [comment]
The rancher/agent is a simple repository on Dockerhub not an Automated Build so I think you need a manual update. The current image is from a few days ago. Could you upload so I can verify the fix.

**Comment by cloudnautique** [comment]
We do manual pushes to Docker hub so the tags/image versions line up.

We do weekly releases on Wednesday. Should be coming out soon, but will be tied to an updated rancher/server:beta

If you are feeling really adventurous, I have a version in cloudnautique/agent:devel 
In order to use it, you need to update the setting: 

http://<your_server>/v1/activesettings/1as!agent.instance.image 

and substitute it in the command that the UI gives you.

to have the cloudnautique/agent:devel entry... This will cause all the agents to update to that version of the template.

**Comment by cloudnautique** [comment]
Actually, you don't need to update the setting. Just use it as the registration image.

**Comment by cloudnautique** [comment]
rancher/agent:latest has been updated to include the fix.

**Comment by usmanismail** [comment]
Verified
