### ISSUE TITLE
Is it possible to run rancher, but not have containers use the rancher network?

### ISSUE THREAD

**Issue by deitch** [rancherio/rancher#1429]
I am exploring rancher for container management and orchestration, and it looks great. My concern is around networking. We use direct to host networking, without even the docker/Linux bridge because of extreme network latency sensitivity.

Can I use rancher to manage the environment, but still have the hosts communicate via the network I set them up with?

**Comment by cjellick** [comment]
@dietch In addition to our managed overlay networking mode, we support all the network modes supported by docker, including "none" and "host."

So, if you are looking for the equivalent of `docker run ... --net=host ...` to get your containers directly onto the host's networking, yes we support that.

**Comment by deitch** [comment]
Hey @cjellick  thanks for the response. I was looking for the networking design and use cases on the Rancher Web site and docs, but wasn't sure.

So it sound like the default mode is that Rancher:

* leaves the Docker bridge in place
* adds its own bridge
* IPSec tunnels its bridge between hosts using whatever host networking fabric is in place, so all of the containers think they are on one big network and can communicate
* Changes ip route inside the container to set the default route to be over the rancher network

Is that right? 

If so, how do I enable/disable that mode (or any other)?

I am also curious why you chose IPSec. Besides the longstanding configuration pain for IPSec, doesn't an encrypted tunneling protocol create lots of overhead?

**Comment by cjellick** [comment]
@deitch, I'm not our networking expert, but I think I can answer most of your questions.

First, yes, we leave the Docker bridge in place. In fact, when using the Rancher managed network, the container is still added to the Docker bridge (and still receives an IP allocated by Docker). To configure the container with a Rancher managed IP, we use nsenter to inject a Rancher managed IP into the container. When I say "inject" I mean we perform (basically) an `ip addr add dev eth0 <rancher managed ip>`. So, when using Rancher managed networking, your container currently ends up with 2 ips: 1 from Docker and 1 from Rancher. We plan to fix this in the future so that your container gets a single IP.

Second, we do not add our own bridge to the host, but we do build IPSec tunnels between the hosts. We do this by creating a network agent container on each host. It receives config updates from Rancher and manages the networking for its host. 

Third, I'm not sure about whether we change the ip route inside the container to make the default the rancher network. I can follow up on that.

Fourth, you can configure the networking on a per container basis. The UI has a networking tab with a Network drop down that gives you all the possible modes, including "None". I don't believe we have a way to completely turn off the rancher network agent, but will verify that.

Finally, IPSec was originally chosen because of its encrypted tunneling which allows us to do cross-cloud-provider networking. We've discussed using a different networking technology such as VXLAN, but we've not seen a ton of demand for it or push back on the IPSec solution.

Does that answer everything to your satisfaction? If you want more details on a particular bit, let me know and I can get the answers.

**Comment by vincent99** [comment]
I believe if you never create a container with `networkMode=managed` a Network Agent never gets created.  The IPSec server runs in the Network Agent containers on each host.

What configuration pain are you referring to?  Because for our users it automatically works with no configuration beyond opening 500+4500/udp.

Encryption is CPU-accelerated and can do at least 2gbps on a modern chipset (with aes-ni).

**Comment by deitch** [comment]
You guys take the prize for detailed responses!

> Third, I'm not sure about whether we change the ip route inside the container to make the default the rancher network. I can follow up on that.

It has to have something to know how to route packets. If the default route is on the 172.16 network, and it wants to send a packet out... oh, wait... right. If the other container just advertises the 10.0 IP address, then it will send it over the Rancher-managed network. Is that it? Just add the route for 10.0 on the Rancher-added interface?

> Fourth, you can configure the networking on a per container basis. The UI has a networking tab with a Network drop down that gives you all the possible modes, including "None". I don't believe we have a way to completely turn off the rancher network agent, but will verify that.

Is there a way to set it as the default? Like I said, our containers are extremely latency sensitive (hence no Docker bridge or vSwitch), so we are directly attaching the interfaces from the host (combo of virtual interfaces and SR-IOV).

> What configuration pain are you referring to? Because for our users it automatically works with no configuration beyond opening 500+4500/udp

I meant on setting it up on your end. I am sure once it is containerized, it is done and well. But I have a long history of suffering through IPSec config. I once met the woman who basically wrote the spec, she told me it was hellish. I go ssl and ssh tunnels anywhere I can. 

It was not a "how do I make this acceptable" question, much more of a "why did you make yourselves suffer through it this way" question. :-) What implementation did we use?

> Does that answer everything to your satisfaction? 

Yes, definitely for now. I will be setting up a bunch of 3-node clusters in the cloud for a client to test various orchestration and management engines. I *definitely* want to present this to them.

Oh yeah:

1. What's the business model?
2. Do I need to sign up for the beta? Isn't it just available on github?

**Comment by vincent99** [comment]
Honestly we had literally the default hello-world example config for raccoon (the IPSec server) until fairly recently (and it was slow, until I switched the encryption to AES).  Maybe it's just because we have explicit knowledge of what host each `10.` IP needs to be sent to or something but running the server and configuring the point-to-point links hasn't been a problem.

I'm sure it's unsuitable for your latency-sensitive application as you said, but for most typical applications it's fast, automatic, and requires no or very simple external configuration.  Docker 1.7 experimental includes support for network drivers, we'll be supporting this too.  

Everything is open-source and beta users are using the same releases; The beta program is just more formally working with the selected companies, identifying gaps in their needs, prioritized development to address them, direct access to engineering (but we're all here anyway...), etc. 

Business plan:
1. Build cool stuff open-source
2. ???
3. Enterprise support
4. Profit!

**Comment by deitch** [comment]
> I'm sure it's unsuitable for your latency-sensitive application as you said, but for most typical applications it's fast, automatic, and requires no or very simple external configuration. 

Really interesting. I think when I set up the testing clusters in the next few weeks, I will set one up with the full networking, just to see. Run traceroute and netperf in the containers and see what happens.

> Docker 1.7 experimental includes support for network drivers, we'll be supporting that too. 

Yes, I thought that was excellent.

> Everything is open-source and beta users are using the same releases; The beta program is just more formally working with the selected companies, identifying gaps in their needs, prioritized development to address them, direct access to engineering (but we're all here anyway...), etc.

I will sign up then, even if just for this client. They are starting the conversion with about 6 containers, quickly ramping up to 60, then will break that out further to hundreds. Management is critical.

But I still don't know: how do I control if containers use Rancher networking or not? Whether on an individual container basis or system-wide?

**Comment by vincent99** [comment]
There's a drop down in the network section when creating a service or container to choose the networking mode.  The default is managed (IPSec) and there is not currently a way to change the default.  From the native docker CLI I think there's a label to opt out of managed (@cjellick?)

**Comment by deitch** [comment]
OK, I am not going to drive you crazy with it. I know it will work without it, I have plenty of other automatic configurations to think about (volumes, tags, etc.). I will get my cluster up and running, and then see where it goes from them.

I signed up for the Beta.

**Comment by cjellick** [comment]
@vincent99 @deitch From the native docker CLI, you are opted out of Rancher networking by default. You have to *add* a label to get a container started by the docker CLI to join the Rancher network.

Canonical example: `docker run -l io.rancher.container.network=true -itd ubuntu bash`

**Comment by deitch** [comment]
Got it, I think. I need to get my cluster up and running and try it in different modes. I think I will get it from there. Hopefully I will be in the Beta, and then we can see if I have more questions.

Thanks for answering everything.
