### ISSUE TITLE
/etc/hosts for linked containers

### ISSUE THREAD

**Issue by indeyets** [rancherio/rancher#237]
Usually, docker manages `/etc/hosts` of containers, by adding records of linked containers there. It doesn't work in my setup with Rancher.

Is it supposed to work? I wonder if it's my local fluctuation or a "feature"

**Comment by naturalethic** [comment]
+1

Why is this not present?

**Comment by GotenXiao** [comment]
I think I've found it - the functionality is there, as it's a Docker builtin. Unfortunately, Rancher overrides the names to be hexadecimal strings, so the usual names are not present. This could probably be solved by passing additional hosts via --add-host when creating containers.

**Comment by GotenXiao** [comment]
Thinking about this issue a bit more, Rancher explicitly has support for overlay networking, so doing a hardcoded link in /etc/hosts doesn't really make much sense - especially since Docker currently doesn't support modifying those entries after container creation. However, it's not clear how the service discovery mechanism is supposed to work, or if you're supposed to modify your applications to use the environment variables (e.g. DB_PORT_27017_TCP).

**Comment by vincent99** [comment]
DNS-based discovery and Docker Compose integration are in the works.

**Comment by vincent99** [comment]
Links are now available in DNS as of v0.20.4 (which is now `:beta` and `:latest`)

For example if you link a container named `mysql` as `db` into a container, `db` will resolve to the IP of the `mysql` host.
