### ISSUE TITLE
[Machine] After the transitioning message shows "Error creating Machine", can the state and transitioning state be turned off?

### ISSUE THREAD

**Issue by deniseschannon** [rancherio/rancher#247]
When there is an error in creating machine, the state of the host remains in "Creating" and the transitioning gear/status bar are still spinning. Also, the "Setting up machine..." text is showing.

Can we update these states/messages to indicate that there is an error and match the transitioning message? This might fall into @will-chan changes for error handling, but wanted to log the confusing messages.

![screen shot 2015-03-18 at 1 23 03 pm](https://cloud.githubusercontent.com/assets/11410997/6718784/7088a346-cd73-11e4-8846-d08ba6db07c0.png)

**Comment by vincent99** [comment]
If there's an error and creating the machine is never going to succeed, the backend should set `transitioning` to "error".  That would make the message show up red and replace the spinner with a :warning: icon.  The `state` should also probably progress to "removed" so that it gets purged eventually, like happens with containers that fail.

The lower "Setting up machine..." will still be shown right now, it's just static text.  Will change to show the `transitioningMessage` in the white area, instead of above the progress bar (which will fix #246 too).

**Comment by vincent99** [comment]
So they will look like this...

![screen shot 2015-03-18 at 3 14 58 pm](https://cloud.githubusercontent.com/assets/753917/6720607/a85a56b2-cd81-11e4-8841-7ed430162c93.png) ![screen shot 2015-03-18 at 3 14 37 pm](https://cloud.githubusercontent.com/assets/753917/6720606/a8591784-cd81-11e4-8c96-cf5b86ccf736.png)

**Comment by vincent99** [comment]
The UI parts are updated in rancherio/ui#98, @will-chan will still need to update the machine backend to set the `transitioning` and `state` correctly though.

**Comment by vincent99** [comment]
This should be done in the backend and UI now.

**Comment by deniseschannon** [comment]
Fixed in v0.14.1
