### ISSUE TITLE
Can you run commands when adding a new container without specifying a user? 

### ISSUE THREAD

**Issue by deniseschannon** [rancherio/rancher#270]
In https://github.com/rancherio/rancher/issues/31, it implies that the user is required if you input a command in the option. 

Is this correct? If so, do we need to update the UI so that it forces the validation before trying to launch the container?

**Comment by vincent99** [comment]
You do not have to specify a user.  The problem is that if you focus the user field, the value stored internally switches from a null to an empty string.  The API accepts null, but not empty string.

#239 was the original issue in rancherio/ui to track this, can we consolidate it with #270 and #96?    There are probably other fields besides name and command where this can occur, but it's one underlying problem.

**Comment by vincent99** [comment]
User is not required and the UI doesn't send empty strings anymore.

**Comment by tfiduccia** [comment]
v0.17.0
Verified Fixed
