### ISSUE TITLE
[UI][Host and Container] - When deleting a container , the delete confirmation page shows with the container detail page launched in the background.

### ISSUE THREAD

**Issue by sangeethah** [rancherio/rancher#274]
Version - V0.12.0

Scenario 1:
From hosts page , pick a container from any host.
Try to delete this container.
Notice that , When deleting a container , the delete confirmation page shows with the container detail page launched in the background.

Scenario 2:

From container list view , try to delete a container.
Notice that , When deleting a container , the delete confirmation page shows with the container detail page launched in the background.

Expected Behavior:
We expect the delete confirmation page to show up on the current page ( host page / conatiner list page) instead of being shown on the container detail page.

**Comment by vincent99** [comment]
This was actually intentional/a side-effect, because the action has a URL (/static/containers/:id/delete) and the routing engine goes through each of the parent routes in order.  But people keep complaining about it, so fine, deletes no longer have URLs.

Note that this affects every confirmation and the sometimes multiple ways you can cause a delete (like delete container from the hosts screen vs host container list vs top-level container list vs container details): apikey, container, host, project, registry, registry-credential, volume.

**Comment by vincent99** [comment]
Changed in rancherio/ui#111

**Comment by tfiduccia** [comment]
v0.14.2
Verified fixed
