### ISSUE TITLE
Process to upgrade RancherIO to latest version

### ISSUE THREAD

**Issue by shankscoder** [rancherio/rancher#302]
What's the correct workflow to upgrade Rancher's container WITHOUT losing configuration data?

I'm assuming since there is no external data binding when running the container, the data related to configuration will not be persistent across version upgrades. How do we sort that out?

**Comment by cloudnautique** [comment]
Good question! We haven't documented the process yet because we are **NOT** officially supporting upgrades between releases before we hit a GA release. The project is still evolving rapidly and we will break things as we move towards GA. 

Recently, we changed default DB backends in release v0.10.x to MySQL from H2. There is no migration plan between the two formats. You can continue to use H2 for smaller environments if you choose, but we recommend moving to MySQL.

The procedure we follow when we upgrade is outlined below. We typically only go from one version to the next if we do upgrade.

1. Stop the rancher/server container. (This container will become your DB server for ever)
2. Back up the data. 
  * Create another container with `--volumes-from=<name_of_old_server>`
  * Copy the contents of /var/lib/cattle to someplace safe.
  * if you are running >v0.10.0 also copy /var/lib/mysql
     ** on containers >=v0.10.0 3306 is exposed and you could publish and create MySQL slaves.
3. launch a new rancher/server container

Its a good idea if you initially deployed rancher/server:latest to do a `docker pull rancher/server:latest` beforehand, or use a specific version. 
  
```
# MySQL
docker run -d --volumes-from=<name of old server> -p 8080:8080 rancher/server:<version>
# H2
docker run -d --volumes-from=<name of old server> -e CATTLE_DB_CATTLE_DATABASE=h2 -p 8080:8080 rancher/server:<version>
```

You can also configure an external MySQL database server by setting these environment variables on the container. This allows you to decouple the server from the DB.

```
    CATTLE_DB_CATTLE_MYSQL_HOST
    CATTLE_DB_CATTLE_MYSQL_PORT
    CATTLE_DB_CATTLE_USERNAME
    CATTLE_DB_CATTLE_PASSWORD
    CATTLE_DB_CATTLE_MYSQL_NAME
```

**Comment by shankscoder** [comment]
So the major bottleneck is the DB then? I would think it makes more sense to deploy using an external DB host for the sake of better manageability. Out of curiosity, why wouldn't this be the recommended deployment config?

**Comment by ibuildthecloud** [comment]
@shankscoder It's only because we have no real "recommended" setup at the moment.  We packaged rancher in a way that we felt was the simplest to get up and running, but it is by no means the best way to run it for production.  Once we release a beta we will have proper instructions for a highly available rancher setup.

**Comment by jmfrappier** [comment]
I just did an upgrade to v0.22.0-rc2 and had to configure a new host as the one i already had was stuck in "connecting". Once i added the host, rancher/agent was at v 7.8 and everything seemed ok. My boss tried to view it and was getting a page that asked to setup an environment. On my computer it showed "machineserviceaccount". I clicked to setup a new environment andocd all of a sudden my host was gone and i couldn't go back to the machineserviceaccount environment. Log shows "ERROR [:] [] [] [] [ecutorService-6] [i.c.p.e.e.i.ProcessEventListenerImpl] Unknown exception running process [agent.reconnect:67] on [2] io.cattle.platform.eventing.exception.EventExecutionException: bea3e22d-8351-4d66-84c3-685f1fc406dc : [Errno 2] No such file or directory: '/proc/3912/environ'"

**Comment by deniseschannon** [comment]
Note: We still don't *support* upgrading Rancher. In the last month or so, there have been major changes in Rancher that will make the process outlined above not work. Specifically, anything prior to v0.18.0 will not be able to be upgraded to any versions afterwards.

@jmfrappier We addressed your question in the Google Groups question.

**Comment by vincent99** [comment]
For those playing along at home, that's https://groups.google.com/forum/#!topic/rancherio/hYLl789gRuw

**Comment by vincent99** [comment]
Updating is now supported starting with the beta release... http://rancher.docs.rancher.com/docs/upgrading/

**Comment by Rucknar** [comment]
Update to the above, that links to rancheros upgrade instructions. For rancher : http://docs.rancher.com/rancher/upgrading/

**Comment by vincent99** [comment]
Thanks; it was rancher at the time but the URLs were rearranged a couple times.
