### ISSUE TITLE
Support github auth

### ISSUE THREAD

**Issue by ibuildthecloud** [rancherio/rancher#303]
It's really confusing hitting the API UI from the browser and then having to type in your access key/api key.  Additionally, if you aren't careful you can create a HTTP session for the UI with those basic auth credentials.  Then all hell breaks loose.

**Comment by vincent99** [comment]
I think to do we'd have to pass the JWT around as a cookie instead of the Authorization header (or completely rewrite the API UI so it's an application that makes AJAX requests instead of a bolt-on to the browser directly making HTTP requests).

Cattle would have to handle login and error cases somehow, e.g. if the token is invalid or expired..  And the API would have to live on the same hostname as the UI (or a subdomain).

**Comment by vincent99** [comment]
As discussed, we can implement this on top of Basic auth by sending a known username like `x-api-bearer` and the JWT token as the password.

@hibooboo2 I think this should be your next thing after finishing the project updates.

If `api.security.enabled` is false then auth of this form should be ignored.  This will fix the weird case @tfiduccia got into today where the browser is stil sending authorization headers but no authorization is required, no hosts/anything show up, and the UI won't let you go to manage access controls because the credentials don't allow it to hit githubConfig.

**Comment by vincent99** [comment]
Username: `x-api-bearer` or `x-api-bearer=PROJECT_ID`
Password: `JWT_DATA`

**Comment by tfiduccia** [comment]
v0.17.0
Verified Fixed
