### ISSUE TITLE
[UI] [Machine] For DO, why are the options limited? What are the default settings for a deployed host?

### ISSUE THREAD

**Issue by deniseschannon** [rancherio/rancher#353]
Version: v0.13.0

Digital Ocean has many options (ie. regions, distributions, settings) that can be picked. How come we don't provide these options when adding a host? If there is a reason, we should add something to the UI to let users know why the choices have been limited. 

![screen shot 2015-03-27 at 12 48 17 pm](https://cloud.githubusercontent.com/assets/11410997/6875844/8da18386-d47f-11e4-8403-13c5f11330df.png)

Also, should there be some description of what applications are also installed? For example, I imagine we are installing Docker on the host as an application, but nothing on our site says what is added by default. 

If we don't add it to the UI, I'd like to document these reasons.

**Comment by vincent99** [comment]
Add Host all goes through [Docker Machine](https://docs.docker.com/machine/).  Each service provider has a driver in there that exposes various options, [here's the ones for DigitalOcean](https://github.com/docker/machine/blob/master/drivers/digitalocean/digitalocean.go).  Those options get mapped into schemas in our API (`digitaloceanMachine`), and the UI exposes controls for those.

Region and Distribution ("Image") are exposed in our API and the UI today.  

The other options under "Available Settings" were added in a newer version of Machine than we are using, and haven't been added to our API yet, so the UI can't set them yet.

They are also somewhat problematic because which options are available depends on the region you select, but Machine provides no way to discover any of that.  The UI has a JSON file with the current regions/sizes/images, I can add it to there but we need to check that it's up to date periodically. (Or hook into the actual DigitalOcenan API outside of Machine and read the available options per region)

**Comment by vincent99** [comment]
Private Network, IPv6, and Backups are options in the UI now.  User Data is required to use Machine so it's not shown.  Machine creates a server from DO's standard Ubuntu images, SSHes into the VM and installs Docker, etc on it.  You'd have to look at the [docker/machine](https://github.com/docker/machine) code to document exactly what is installed.

**Comment by deniseschannon** [comment]
V0.16.0 - Regions/Extended options are available. 

I have added notes on what to add in the docs.
