### ISSUE TITLE
[UI][host] - "Add Host" option is not visible on the "Hosts" page when there are lot of host entries.

### ISSUE THREAD

**Issue by sangeethah** [rancherio/rancher#440]
Server version - V0.14.2

When there are large number of hosts  (> 10) , "Add Host" option gets added as the last entry after all the existing hosts. User needs to scroll down to get to this option.

It would be more convenient to have the "Add Host" option show up in the beginning of the host list . This way it is also present in the same place irrespective of the number of hosts.

**Comment by vincent99** [comment]
@ibuildthecloud and I don't like moving the dotted box to the beginning because it takes up space all the time for something that you only need occasionally.  I talked to Nikita and we plan to add an Add button at the top of each section:

![image](https://cloud.githubusercontent.com/assets/753917/7014446/c5de87f6-dc79-11e4-895f-c24eb7a77924.png)

**Comment by tfiduccia** [comment]
v0.16.0
Verified Fixed.
