### ISSUE TITLE
[UI][LB] Removed LB is only sometime showing up on LB page

### ISSUE THREAD

**Issue by tfiduccia** [rancherio/rancher#451]
v0.15.0

Steps:
1.  Create a new LB
2.  Remove the LB and wait a couple of minutes
3.  Refresh the Page (the removed LB goes away)
4.  Go to Config page and back to LB page

Results:
The removed LB shows back up

Expected:
Not sure if it's supposed to stay or not.  But it should do the same thing.

**Comment by vincent99** [comment]
Related to #297 / #384.

**Comment by vincent99** [comment]
They were showing up if you had gone to the config page because the config references the removed balancer because of the referenced bugs, which loads them into the UI's list of known balancers.  Then when you go back they'd get displayed.  Removed balancers are now filtered out of the display (regardless of how they got into the list)

**Comment by tfiduccia** [comment]
v0.16.0
Verified fixed
