### ISSUE TITLE
[UI][LB] - Not allowed to add new LB configuration without listeners.

### ISSUE THREAD

**Issue by sangeethah** [rancherio/rancher#471]
Server - build from master on Apr 7

Steps to reproduce the problem:
Create a Load Balancer configuration , by not entering any values for listener.

Creation of Load Balancer fails with - "Validation failed: targetPort" error message.

Should we be allowed to add a new LB configuration without listeners ? Or provide the ability to choose from existing list of listeners?

**Comment by vincent99** [comment]
You can't create a *useful* balancer without one, and @deniseschannon suggested defaulting to one line for a listener to emphasize that.  You should be able to delete the line if you really want no listeners, but you can't just submit with invalid/empty values.  Which should be caught before you actually submit, because you'll find you're creating a loadBalancerConfig every time you try this (#448)

**Comment by sangeethah** [comment]
We should be providing the ability to choose from existing list of listeners , when creating a Load Balancer configuration. API allows for this .Should we be exposing this functionality?

**Comment by vincent99** [comment]
@sangeethah: @alena1108 and I decided against showing reuse listeners and it will probably be removed from the API/changed to an embedded array in the config at some point.  Of all the things you have to set for a config, being able to reuse a couple port numbers doesn't seem that valuable.

**Comment by vincent99** [comment]
UI now requires a listener (and target, and host)

**Comment by tfiduccia** [comment]
v0.16.0
Verified Fixed
Listener is still required.
