### ISSUE TITLE
Access key and Access Token values should be masked in the UI

### ISSUE THREAD

**Issue by sangeethah** [rancherio/rancher#518]
Server version - V0.16.0

"Access key" value in Digital Ocean "Add Host" page and "Access Token" value in Amazon EC2 "Add Host " page appear in clear text.

The values entered for these fields need to be hidden.

**Comment by vincent99** [comment]
EC2 Access Key is essentially a username.  It should definitely not be hidden.

I don't even think the secret key/access token should be hidden, really.  They are 40-64 character random strings, not user-provided passwords.  Nobody types them, you copy and paste them and hiding the text makes it hard to tell when you've accidentally pasted the wrong thing.  You won't find out the credentials are wrong until you've submitted the form because we can't check them ahead of time.

**Comment by vincent99** [comment]
Secret values are now `<input type="password">`.  I still think it's less usable, but it's hard to make a screencast if your secrets are visible.
