### ISSUE TITLE
Deleting and restoring a service's container loses association with service

### ISSUE THREAD

**Issue by tfiduccia** [rancherio/rancher#527]
v0.16.0
Steps:
1.  Create a Environment
2.  Add a service
3.  Go to Container page
4.  Delete and restore service container
5.  Go back to Service page

Results:
Service container no longer shows up.  If I delete and restore from service page, it stays.  If I delete from service page, but restore from container, it's removed.

Expected:
Should stay until purged.

**Comment by sangeethah** [comment]
Even when we attempt to delete and restore from service page, the container is removed from the service. Notice that when you refresh , the service does not have this container associated with it anymore.

Removing UI tag from this bug , since it reproduces from both the container view and service view.

**Comment by tfiduccia** [comment]
v0.18.1
Verified fixed
