### ISSUE TITLE
Hosts list becomes empty with new host connected

### ISSUE THREAD

**Issue by nazar-pc** [rancherio/rancher#592]
While being on page `/static/hosts` when new host is connected list just become empty, including add host tile.
After page refresh all hosts are present as it should be, problem is only when new host is connected.

**Comment by vincent99** [comment]
@nazar-pc What version of Rancher ar eyou running?  I think we fixed this problem a few versions ago and have not been able to reproduce it on v0.17.0

**Comment by nazar-pc** [comment]
Latest, just installed today from `rancher/server:latest`

**Comment by nazar-pc** [comment]
Image `3e91cb8f0168`, don't know how to see exact version

**Comment by vincent99** [comment]
`:latest` is currently v0.16.2..  We really need an 'about' page that gives you the exact versions of things.. but anyway you can right click -> "view page source" to see the UI version (in the `<script>` tags), which is what we're interested in at the moment.  `3e91cb8f0168` looks to be the correct image id for 0.16.2 though.

A few random questions to try and track it down:
  - Do you have github access controls enabled?
  - If yes, in your default project or another?
  - How are you adding the host?  Via machine for DigitalOcean/EC2, or with the "custom" `sudo docker run ...`?
  - If you resize the window (enough that the number of columns the UI displays changes) doe they come back?

**Comment by nazar-pc** [comment]
Indeed, version is 0.16.2 (BTW, why don't you bundle assets with image?!).
* No GitHub access.
* With "custom".
* To resize I have to add host. But after I've purged it I can't add it again, it just doesn't appear in dashboard...

**Comment by vincent99** [comment]
There's a few reasons but mainly because it's easier for us to deploy independently of the backend.  It doesn't update automatically, but there's a setting for where Cattle loads the UI that can be tweaked without doing a Cattle update (and a `/ui/latest` that will always give you what's in rancherio/ui master). Another thing is we have other externally-hosted dependencies anyway, notably one of the icon sets is commercial and we can legally "host" it but not "distribute" it.

I just meant resizing the browser window.. There's some logic for how many columns wide the display should be depending on the size of the browser window, and shrinking it down enough to change the number of columns would cause it to re-render all the columns, if it's just a view-layer problem.

I haven't been able to reproduce this with 0.16.2 though still, what browser/version/os?  Thanks

Regarding not being able to re-add a host once it's been purged, the host remembers it's UUID in `/var/lib/rancher/state` (in hidden dotfiles) and the server remembers the host with that UUID is purged.  So to re-add a host that was previously used, `rm -rf /var/lib/rancher/state` on it, then run the `sudo docker run...` from custom add host again.

**Comment by nazar-pc** [comment]
Yes, resizing helps, the reason why it becomes empty is because of JS error:
> TypeError: this.importLink is not a function ui.js:11:20023

Source is minified, so you have to find that place in original file)

Would be nice to see purged hosts somewhere in UI)

**Comment by nazar-pc** [comment]
Browser Firefox Nightly 40.0a1 (2015-04-22), Ubuntu 15.04 x64, actually it is installed on local machine, and I'm adding this host machine so that both server and agent are under the same Docker on the same machine.

**Comment by vincent99** [comment]
Ah, great that JS error helps.. This was actually fixed a couple days ago in rancherio/ui@c88475c6195b1b801fbb74f6214f1e92e9f03456; If you're feeling adventurous it's included in `rancher/server:v0.17.0`, but there are a couple bugs still being worked out that will be in a `v0.17.1` tonight.  After that it should become `:beta` probably tomorrow and `:latest` by Monday.

**Comment by nazar-pc** [comment]
Awesome, I have nightly builds of everything that can be nightly using repositories (I only compile kernel by myself), so, I'm OK with testing pre-apha state code)
Since this was already fixed it should be released by Monday, I'm closing issue, thanks for info.
