### ISSUE TITLE
Deleting default and re-entering will create new project

### ISSUE THREAD

**Issue by tfiduccia** [rancherio/rancher#595]
v0.17.0 (have auth on)
1.  Rename default project to Project1
2.  Create a new project called Project2
3.  Set the default to Project2
4.  Delete Project2
5.  Exit out and re-enter (I actually re-entered in separate browser)

Results:
Created a new Project called admin Default and made it the default

Expected:
Should see I have another project and set that one as default and not create a new one

**Comment by vincent99** [comment]
@hibooboo2 Only create a new default if there are no other active projects the user has access to?

**Comment by hibooboo2** [comment]
Had that logic must be flawed will fix.

**Comment by vincent99** [comment]
This also doesn't work well if the user's default project still exists but is inactive.

**Comment by hibooboo2** [comment]
Per discussion with @ibuildthecloud :

Always have default project. 
Cannot delete your default project. 
If you don't have a default then you get a 403 unless sending x-api-project-id=user then you can list project and use that to select a default or you can create one with the api if you can't access any. This is not magic or automatic.

I will write tests for this.

On delete we check if you are trying to delete your default and you get status code 406 if you are.

If your default project is not found you get a 403.

**Comment by ibuildthecloud** [comment]
@vincent99 in short we try to never let the user delete the default project.  They must select a different default project before deleting.  This doesn't handle the case where somebody else deletes the project that is default.  In this situation you should make the user choose a default or if there are no projects, create a new one.

**Comment by vincent99** [comment]
This isn't exactly related but I really don't think the `x-api-project-id` scope stitching is working well at all.  Why do we need the if-requested-with-account-key-pretend-requests-are-for-the-default-project behavior at all?  Who needs this, existing tests?

If the account being authorized was just the account in the auth header (an API key on an account or one on a project for Basic apikeys, and the account for Bearer/token) unless a project I'd is was specified (header, query param, x-api-bearer= username) then the "default project" would just be a UI setting that the API doesn't need to know anything about and the `=user` could go away.

Doesn't a user who is implicitly whitelisted get locked out if their last project is removed?  If not shouldn't they?  How do I get rid of someone that was previously granted access?

If User A deletes, deactivates, or removes the a projectMember from a project, it is impossible* for us to tell if this is the last project user B had access to (it can include members that user A can't see the user list of).  So you can't decide to recreate or set new defaults or anything on delete.

The UI already has code to pick a project if I don't find the default, or force them into the projects page to create a new one if there were none (only if you are admin, because I thought you'd be locked out otherwise).

*: if we stored access tokens on login for each user into the DB then you could use those to determine user B's memberships from user A.  This would also allow an account API key + project is header to work (#272)

**Comment by ibuildthecloud** [comment]
Okay, don't know if I followed that.  But yes =USER should be the default behavior and just get rid of that magic flag.

Why do we even have a default project?  Why do we magically create projects for users.   If anything the default project can be created by the UI automatically on first access.

**Comment by ibuildthecloud** [comment]
A white listed user can't really get removed because we allow them to create other projects.

**Comment by ibuildthecloud** [comment]
The "magically" switch to default project is what broke all the tests.

**Comment by ibuildthecloud** [comment]
I don't think we should expose project switching from the API yet.  It's best to just create api keys per project.

For project switching it seems like v1/projects/:id/containers should work if you are using an api key for a user. And not a project.  We can do that later.  API keys per project don't seem that bad to me in the short term

**Comment by vincent99** [comment]
So auth:
 - [ ] Remove `x-api-project-id: user`
 - [ ] Remove `defaultProjectId` from backend code, I'll save it in the browser
 - Authorize request as "the user" when sent:
    - [ ] `?token=[jwt]`
    - [ ] `Bearer: [jwt]`
    - [ ] `Basic: x-api-bearer:[jwt]`
 - Authorize request as "a project" when sent:
    - [ ] `?token=[jwt]&projectId=[projectId]`
    - [ ] `Bearer: [jwt]` + `x-api-project-id: [projectId]`
    - [ ] `Basic: x-api-bearer=[projectId]:[jwt]`
 - Authorize request as whatever accountId the key is for when sent:
    - [ ] `Basic: [api accesskey]:[secretkey]`

Still need to figure out the default project creation and how that interacts with `access.mode=restricted` and the user isn't on the whitelist.  Maybe we can just get rid of "[username's] default" and let the user make their own project if they want one.  If the last project the user has access to is deactivated, then shouldn't they just not have be authorized to login anymore?

**Comment by ibuildthecloud** [comment]
If the user has to create the first project in the UI I'm totally fine with that.  If the user is not authorized to any project and is not in the whitelist, they are locked out.

**Comment by vincent99** [comment]
Ok, so cattle will create only the one default project during install, and not have any other magic.  And it can be called just "Default".

Can we get rid of the `rancher_id 1a1` projectMember too then?  That showing up in the members list after turning on auth is a source of confusion.  
 - [ ] With access control disabled, just allow access to any active project.
 - [ ] When access control becomes enabled, add projectMember `github_user [user that is turning auth on]` to all the not-removed projects.

**Comment by tfiduccia** [comment]
v0.19.2
Verified fixed
