### ISSUE TITLE
When containers that are part of services are renamed , renaming the service renames the containers.

### ISSUE THREAD

**Issue by sangeethah** [rancherio/rancher#651]
Server Version - V0.18.1

Steps to reproduce the problem:
Create environment.
Add a service.
Change the name of one of the containers (c1) to say "abc"
Change the name of service/environment.

This results in the name of c1 to be changed to envname_servicename_index format.

Since there was an explicit edit of container names , should we not be editing the name of this container  as part of service/environment name change?

**Comment by alena1108** [comment]
Its by design. If user renames the service/environment, all the instances within it should get renamed. We don't treat user defined name for a single container as some special name; we let it be only till the moment user redefines it on the higher (service/environment) level. Very similar to the case when instance gets destroyed - we preserve instance->service mapping till any operation is called on the service (activate/deactivate)
