### ISSUE TITLE
Rancher Basic Test Plan for LB Services

### ISSUE THREAD

**Issue by will-chan** [rancherio/rancher#729]
* Add basic test plan for LB Services.
* Fix any related test plans for UX changes in private registry support.

**Comment by defunctzombie** [comment]
I've been testing out the 0.19 tag and it seems that when I create a load balancer the host ports don't get exposed on the host. Not sure where else to post this issue since 0.19 was only recently tagged.

Running rancher server 0.19 and an agent on the same vm (inside boot2docker). Everything launches correctly and I can make the lb no problem but it doesn't do anything with the ports I configure on the load balancer even after it says the LB is active.

**Comment by cloudnautique** [comment]
There is going to be a v0.19.1 soon... The agent version in 0.19.0 is incorrect

**Comment by defunctzombie** [comment]
@cloudnautique cool, let me know if you want it tested again.

**Comment by defunctzombie** [comment]
@cloudnautique btw, tried 0.19.1 and same issue.

**Comment by cloudnautique** [comment]
More fixes coming.. if we don't tag a release with 'beta' pretty quick, it hasn't passed validation tests... just FYI

**Comment by defunctzombie** [comment]
:D

**Comment by will-chan** [comment]
- EC2 
- Host Label/Container Label
- Redesigned Services page.

**Comment by defunctzombie** [comment]
Something that has come up while I was playing with the LB service features in new rancher releases is the ability to put the LB on a specific host or set of hosts. Right now, you can't specify what host the "service" based LB launches on. This makes it impossible to configure external DNS to point to said hosts for terminating the connection since the hosts could be changing.
