### ISSUE TITLE
UX / Save the Digital Ocean key under "API & Keys"

### ISSUE THREAD

**Issue by keyscores** [rancherio/rancher#762]
Shouldn't the Digital Ocean key be stored under "API & Keys"? 
Currently, every time I launch a new host I need to look this up, while it could have been stored.

**Comment by vincent99** [comment]
Our current feeling is we don't really want to be in the business of storing 3rd party credentials in our database.  This might be an option once we add pluggable encryption for sensitive fields (in the next few weeks).  

But my immediate plan is to add storing the credentials into the browser's temporary `window.sessionStorage` or persistent `window.localStorage` (#494) so that they are at least saved locally instead of having to fill it out repeatedly.

There is also a 'Quantity' option when adding a docker machine host as of v0.19 (which is not released/tagged beta yet, but will be available this week).  So you can create several machines at once without going through the whole form again now.

**Comment by keyscores** [comment]
So on a small tangent, you say we'll be able to start several machines. What happens if one machine goes down permanently (over x minutes), could you spawn a new one it its place?
IMO there should be a way to set the minimum number of containers to be running, AND the minimum number of hosts running. Is this in he roadmap?

**Comment by vincent99** [comment]
A minimum number of containers will be possible before our beta launch by creating a service and setting a scale.

Doing the same with hosts is not currently on the roadmap.  If you wanted you could implement this outside of Rancher by calling the machine API, or completely outside of Rancher by just creating machines in $provider through their API and having cloud-init or similar run a script that installs Docker and registers the host into Rancher on startup.

There will be some nasty failure cases to think about... e.g. if the hosts are still actually up but the server running the auto-scaling becomes partitioned.  Or if more than one host disappears it's likely that provider is having a problem, so spinning up a new one might fail too.  And of course any actions you take cost actual money, so there should be limits on how many times it tries.

**Comment by keyscores** [comment]
Thanks for the explanation. Is there a way I create a service and minimum scale in the web UI at the moment?
About you failure scenarios.
1) If the server running autoscaling fails, the recovery is something Rancher will have to address regardless of this specific case.
2) True, if the VMs are failing on digital ocean it may not be helpful to run more. But as a High Availability feature, it would be great to spin up more machines on AWS (or alternate vendor), in cases of catastrophic failure. Rancher is already 95% there with networking features.
