### ISSUE TITLE
Increasing scale of hosts naming is strange if my name ends in a number. 

### ISSUE THREAD

**Issue by deniseschannon** [rancherio/rancher#827]
V0.20.2

When I choose to scale my hosts, the naming convention is not consistent with how we scale up for services. It's strange to me how it's currently implemented, which is basically increasing the last number if a number exists. I'd rather have it append to whatever name I gave. 

Examples of what we do today:
Name: denise1
Scale of 3: denise1 - denise3

Name: denise4
Scale of 3: denise4 - denise 6

Name: denise25
Scale of 3: denise25 - denise27

In services, when we scale, we end up having containers name 

envname_denise1_1
envname_denise1_2
envname_denise1_3

We should move the host naming to the same convention as container naming.

**Comment by vincent99** [comment]
No, this is intentional additional logic programmed in.
  - If you create 3 hosts today they get called denise1 thru 3.
  - If you want 3 more tomorrow you probably want them to be named 4-6.
  - If I just do {name}_1 thru {name}_{quantity} it's impossible to use quantity>1 and have a contiguous set of names.  This enrages people that like order :smile:
  - You can also add 0-padding for even more order, e.g. denise001 will do 001-003.
  - (underscore is not a valid name character for some of the machine drivers)

**Comment by deniseschannon** [comment]
We should do a poll because I can understand what you are saying, but I still don't like it. :)

Service name scaling doesn't follow the same logic, which is also enraging. :)

**Comment by vincent99** [comment]
It's not called scale, it's called quantity :-).  The way it is lets you do either way (if you want `denise3-1` - `denise3-3`, put a hyphen at the end of your name and you'll get what you want).  The other way it's impossible to get 4-6.
