### ISSUE TITLE
Deleting GCE host doesn't delete VM in GCE

### ISSUE THREAD

**Issue by deniseschannon** [rancherio/rancher#839]
V0.20.x

Steps to Reproduce:

1. Link GCE host to Rancher
2. Deactivate host
3. Delete Host

Result: Host is removed from Rancher UI, but VM is still running with all containers on it. 

Expected Result: Host to be deleted from GCE. This is the behavior of Digital Ocean hosts.

**Comment by sangeethah** [comment]
In case of a GCE host , it is a custom host where Vm already exists and user installs rancher agents to connect to Rancher server.
In this case , when hosts are deleted from rancher server , the expected behavior is to just remove the host association from rancher server.

This is different from the case of Digital Ocean hosts where the host (VM) itself is created by rancher server. In such cases , the expected behavior is to delete the Vms  when hosts are deleted from Rancher server.

**Comment by vincent99** [comment]
Regardless of the provider, if the VM isn't created thru Machine then we have no credentials to use to remove it.

**Comment by deniseschannon** [comment]
That makes sense. I found a different bug when testing this kind of scenario. If I remove a host from Rancher, but then try to add it back in using the custom command, it's not connecting back to Rancher.

I've tried stopping the container and running the command again. Containers are running on my host, but doesn't show up in my Rancher. I've logged a different bug for it. https://github.com/rancherio/rancher/issues/843
