### ISSUE TITLE
Sync and import functionality/use cases

### ISSUE THREAD

**Issue by cjellick** [rancherio/rancher#842]
This issue summarizes the import and sync logic for containers. The table below shows how sync and import should work when the state of a container in rancher does not match up with the state of the container on the host. The X axis is the state of the container on the host and the Y axis is the state of the container in rancher.

 | Running | Stopped | Destroyed
---|---|---|---
**Running** | *States match* | User container, mark it as stopped in rancher. System container, restart it so that it actually starts on the host. | <--Same. |
**Stopped** | User container, mark as running. System container, force stop it on the host. | *States match* | *Do nothing* |
**Removed** | Force stop on the host. | *Do nothing* | *Do nothing*
**Not in rancher** | User container, create it in Rancher. System container, force stop it. | User container, create it in Rancher. System container, do nothing. | *Do nothing* |
*A "system container" is one that rancher created for supporting rancher functionality. These include rancher-agent, rancher-agent-state, Network Agent, and load balancer containers.*

Other use cases to consider:
* I start rancher-agent (RA) on new non-rancher host and all containers are imported into Rancher.*
* I want to transfer ownership of a host to a new account. I stop/remove account A’s RA and deploy account B’s RA. All new resources are created.*
* I completely blow away the Rancher DB and restart world. All containers are successfully imported.*
* RA is stopped on an existing host and I create a container. When RA is started back up, the container shows up in rancher.
* RA is stopped on an existing host and I destroy a container. When RA is started back up, the container is marked as stopped in rancher.
* RA is stopped on an existing host and I start a container. When RA is started back up, the container is marked as running in rancher.
* The network agent is stopped. Rancher detects that and restarts it.

*When an environment is re-imported or “transferred" pre-existing system containers are stopped so they don’t conflict with the new ones.

**Comment by sangeethah** [comment]
Tested the following scenarios using server version - v0.22.0-rc1
For regular containers:

Use case 1:
Container in Running state in “Rancher”:
From host:
Stop the container —> Marked as “stopped” in rancher.
Destroy the container —> Container marked “Removed” in rancher and then got purged

Use case 2:
Container in Stopped state in “Rancher”:
From host:
Start the container —> Marked as “running” in rancher.
Destroy the container -> Container marked “Removed” in rancher and then got purged

Use case 3:
Container in “Destroyed” state in “Rancher”:
Start the container —> Another container entry gets created which moves from running to stopped state. — BUG - #933


For system containers:
Use case 1:
Container in Running state in “Rancher”:
From host:
Stop the container —> Network Agent gets recreated.
Destroy the container -> Network Agent gets recreated. But it gets stuck in “Creating” state - BUG - #931


Use case 2:
Container in Stopped state in “Rancher”:
From host:
Start the container - Blocked by BUG -  #931
Destroy the container -  Network agent continues to be in stopped state. After this I am not able to start the agent from rancher server because of bug - #931

Use case 3:
Container in “Destroyed” state in “Rancher”:
From host:
Start the container-> Container starts but exits. Container continues to remain in “Destroyed” state.

**Comment by sangeethah** [comment]
Tested the following use case:
I want to transfer ownership of a host to a new account. I stop/remove account A’s RA and deploy account B’s RA. All new resources are created - #1102 logged.

**Comment by sangeethah** [comment]
Have multiple containers on the host (even before host gets added to the rancher server).
Start rancher agent on this host.

When the host registers successfully in rancher server , all the containers get synced as well.
