### ISSUE TITLE
Add support to label a host when adding via UI

### ISSUE THREAD

**Issue by will-chan** [rancherio/rancher#957]
Support the ability to pass in a host label when adding a machine via the "Add Host" UI.  This label should be passed during the rancher agent bootstrapping phase.

**Comment by vincent99** [comment]
How is this going to work for machine drivers vs custom `docker run...`?

**Comment by sonchang** [comment]
My current thoughts are to specify the label(s) as query params in the host registration URL.  This provides us with at least some type of standard escaping for key/values.  Thoughts?

**Comment by will-chan** [comment]
queyr param is fine.  Do you have the exact label/syntax so we can fix the go-machine-part?

**Comment by sonchang** [comment]
Actually, slight change (rather than putting it in the actual registration URL, moving it to an environment variable).  Will still keep the query param formatting and encoding though.

So something like this:
sudo docker run -d --privileged -v /var/run/docker.sock:/var/run/docker.sock -e "CATTLE_HOST_LABELS=group=web&foo=bar" rancher/agent:v0.7.8 http://localhost:8080/v1/scripts/A8D9E877D4CD093B8D3D:1432936800000:McwiGo3IIXLzjFRpYs4Ni9PDq08

**Comment by will-chan** [comment]
ok, sounds good.

**Comment by vincent99** [comment]
That works for me.. so actual urlencoding?  i.e. if a label value is `adsf $&qwer` then I send you `adsf%20%24%26qwer`

**Comment by sonchang** [comment]
yeah.  i figure it should work well with environment variables

**Comment by sangeethah** [comment]
Tested with v0.23.0-rc1

Able to add custom hosts with labels by using the host register URL that is being provided after entering 2 labels. 

When hosts show up in the UI , the 2 labels are set in the hosts.

Able to add Digital Ocean machine by passing host labels by passing labels as CATTLE_HOST_LABELS='name=value'.

When hosts gets to active state, the labels that were passed during creation  are set in the hosts.
