### ISSUE TITLE
v22 UI confusion between Projects and Environments

### ISSUE THREAD

**Issue by keyscores** [rancherio/rancher#989]
This is not really an issue, just a way to give you guys some feedback on user experience.

The overall distinction between services and infrastructure in v22 is nice. Much clearer, thanks.
However, environment vs projects is less successful...

It's not intuitive for me, that a 'project' is a superset of services. Or even, why I would need a set? Am I to be running multiple projects on the same infrastructure? Is this the best pattern?

In my mind a project would comprise: services, infrastructure (and the different infrastructure environments ).
Also, I'm not sure why the environments set up is to the top right in the menu (along with account information). 

Anyhow, all this to say this new UI threw me off. I would strongly consider simplifying this, and maybe not having the distinction of 'Project' and 'Environment'. 

Hope it's helpful feedback.

**Comment by hrwebasst** [comment]
I'd agree there is some confusion in the current layout.

**Comment by vincent99** [comment]
Docker compose calls a group of services a "project", so we changed to use their term.

An "environment" is a grouping of infrastructure resources (which then run services/containers).  You'd have more than one to keep things like development vs production physically separate.  They're almost like totally separate accounts but can be shared among multiple people.

**Comment by ibuildthecloud** [comment]
We aren't really sold on the naming either and really welcome feedback in this area, we've gone back and forth quite a bit.  Basically we have two things we are working with:

1. Docker compose groups services into a "Project."  In order to have good parity with Docker Compose we felt it would be confusing if we didn't call a group of services projects.  There really isn't a huge need to group service except that it helps to organize them a bit.  The forth coming rancher-compose has pretty close to 100% support for everything docker compose does, so we needed this concept.

2. In order to share things between different users we needed some bucket of resources to share.  Technically, under the hood it is just an account.  You log in w/ github and you have access to multiple accounts that own resources.  This is currently what we are calling environments.

We are up for different names or concepts if you have suggestions.

**Comment by keyscores** [comment]
Thanks for the comments.
In real life I'm not sure anyone will have multiple groups-of-services per environment. Seems like a "nice-to-have" for some people, which is getting in the way of newbies. IMHO
@ibuildthecloud as you say "There really isn't a huge need to group service except that it helps to organize them a bit"

**Comment by deniseschannon** [comment]
@keyscores @hrwebasst: thanks for your feedback on your user experience. we love this kind of feedback as we are definitely still debating on what these items should be called. if you have any further suggestions, please feel free to open another issue. as of this time, we're going to see how the concept of projects/environments work out. since we only made the switch in the last couple of weeks, it might the most confusing for those who have been working on rancher the longest as we just flipped the names. hopefully as you get used to playing with rancher, you'll get used to the names. honestly, i have to always clarify what i'm referring to when talking to others. :)

**Comment by jonpugh** [comment]
I have to agree with everything here. As the author of [devshop](http://drupal.org/project/devshop) and an [aegir](http://aegirproject.org) maintainer I've dealt with a lot of naming confusion over the years as well. 

If you don't mind, here's my analysis and suggestion on how things should be organized:

- **Account:** (Currently known as "Environment") (Option: Organization)
  - An account is what owns projects and hosts, and restricts access to it's members. I think I read somewhere, that they used to be called Accounts?  I think that is a much better word for it's usage. It's analogous to GitHub Organizations.
- **Project:** (Currently known as "Project")
  - The app or system you are running. It's services are represented by it's docker-compose.yml file
  - Each must have a unique name within the rancher server. 
  - "Projects" should replace "Services" in the main navigation.
  - A "Project" is analogous to GitHub Repos.
- **Environment:** (Currently known as "Project")
  - An "environment" is a single instance of a project, created from a docker-compose.yml file.  An environment is the group of containers created from the docker-compose file.
  - When you are developing an app, you will want to instantiate that app in one place for production use, and in others for testing and development.  Each running instance of your Project is called an "Environment". 
  - An environment must have a unique name within a project: "dev", "testing", "production".
  - The containers would be named after their project, environment, and service, for example *projectname_production_database_1"
  - Each environment within a Project will be mostly the same, however sometimes a new dev environment will have new services attached to it, and when proven to work, those new services will be deployed within the production environment.
  - It should be easy to "clone" an entire environment within a project for testing and development purposes.
  - Each environment should have access control, allowing admins to decide who can manage which environment.

As for bringing back "Accounts", I think you guys actually already think of them that way..

As @vincent99 said about the thing currently named "Environments":
> They're almost like totally separate accounts but can be shared among multiple people.

As @ibuildthecloud said:
> In order to share things between different users we needed some bucket of resources to share. Technically, under the hood it is just an account. You log in w/ github and you have access to multiple accounts that own resources. This is currently what we are calling environments.

Let's keep this discussion going!  I'm going to figure out how to help and submit a pull request, eventually!

**Comment by vincent99** [comment]
Internally all resources are owned by an "account" but they're never called that in the UI.  Both "users" and "projects" (the current one, dropdown in the header) are actually differentiated kinds of "account".  "Organization" conflates with Github orgs, which can be members of a project.

"Project" is pretty much not going to change (again).  Docker uses it that way, we want to match their terms.

I don't think a third concept improves the situation :smile:, or that a lot of other people would agree with your proposed definition of environment.  Enterprise-y companies tend to think of environment as dev vs test vs prod and being separate hardware (i.e. hosts) totally isolated from each other, with access to a small(er) set of operations employees, and maybe with firewalls between them so that a developer can't accidentally mess up prod while playing with dev.

Most of your points about what you call "Environment" are true today except for the terms... What you're describing as a separate term "Project" is just a (current-term project that) happens to be named "dev" or "prod".  The docker-compose.yml is generated based on the current project, it's not a first-class resource.    You can create another instance of your app by running `rancher-compose -n anothername docker-compse.yml`, and eventually something like this in the UI.
