### ISSUE TITLE
UI for load balancers - comments

### ISSUE THREAD

**Issue by keyscores** [rancherio/rancher#990]
The built-in load balancing is very powerful, one of the key advantages of Rancher. 
However there is a bit of unnecessary manual configuration occurring which other services forego (see Tutum's implementation). 
For example, if I set a service to scale of 5 the UI could assume that I need a load balancer for this, and either A) start one with smart defaults, or at the very least B) prompt for the load balancer UI form.

Lastly from an infrastructure point of view. Since you are running a networking container on all instances, is there a reason all instances couldn't also be loadbalancers? That is, I could point to any-ip:80 and get my app, any-ip:3000 and get my DB.

All this would be much simpler to get up and running fast.

**Comment by alena1108** [comment]
Those are good questions. Here is the answer to the second one: Why Rancher doesn't configure LB on network system instance.

Main reason for segregating lb instances from other cattle system instances, was to support running LB as a service. So each LB instance will participate in Service Discovery, and it will have its own ip address and would represent DNS A record.

**Comment by keyscores** [comment]
Ok so this may be a silly question.
Why not run load balancer on all instances for the sake of simplicity? It
can still be a service as you mentioned. But it would be managed by
rancher, just like the networking agent.

**Comment by vincent99** [comment]
Suggesting a balancer when creating a service is something we could do.  Not every service needs balancing though.  For example worker processes that read from a queue and run something like video encoding jobs.. they connect out to a queue, nobody connects directly to them.

It is not really practical to create a balancer automatically, as we don't know things like which ports should be exposed publicly, what protocol they speak, how to health check them, etc.

Services do get internal DNS entries for their name.  If you have service1 linked to service2 then you can lookup `service2` or `service2.rancher.internal` on service1 and you will get back A records for each of the containers in service2.  Most client libraries will pick one of them at random to connect to ("round-robin DNS").  We will likely have a way to map this to a public name that can be resolved externally in the future.  This is, as far as I'm aware, what Tutum is doing.

Assigning <every host ip>:80 to a balancer would mean that only one service/container could use public port 80 on your entire infrastructure.  Tutum defaults the ports to "dynamic" so that there aren't conflicts, but if you want port 80 then there can be only one container using that per node.

(also re: #989, note that they also have multiple groups of services called "stacks", === compose/rancher "project".  Except they segregate them from UI-created services and you can only define a stack by editing yaml.)

**Comment by alena1108** [comment]
Besides different orchestration and management flow, there are certain prerequisites for Rancher System instances. One important one: Load Balancer thirdparty software - we use haproxy - has to be enabled on the instance image. And Rancher manages haproxy software by configuring it with the parameters - LB ports/targets- defined by user. In other words, we can't treat any user instance as a potential Rancher specific service provider.

**Comment by deniseschannon** [comment]
@keyscores thanks for your feedback! i hope @alena1108 and @vincent99 was able to address your questions/concerns on the decisions that have been made for Rancher regarding load balancers, if you have any other questions, please feel free to re-open or add a new issue!
